### ISSUE TITLE
[Feature Request]: Pipelines: populate names for the user

### ISSUE THREAD

**Issue by jgarciao** [opendatahub-io/odh-dashboard#1299]
### Feature description
Consider problem from the following ticket in the solution 
-  https://github.com/opendatahub-io/odh-dashboard/issues/1682 

In Data Science Pipelines:
- when importing a pipeline, pipeline name could be automatically populated from the yaml's file metadata
- when creating a pipeline run, run name could be automatically populated. For example, the ds-pipelines-ui automatically sets run name as  _Run of PIPELINE_NAME (f099a)_

**Comment by bdattoma** [comment]
I would like to add an additional case falling under this same Feature Request.

`when creating a pipeline run from DS Project details page, pipeline name in the dropdown could be automatically populated`

Because we have the `Create run` link/button for every pipeline:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/1850e449-bd2c-4ebf-96c4-f1d73d67556d)

**Comment by Gkrumbach07** [comment]
@kywalker-rh awaiting UX

**Comment by andrewballantyne** [comment]
@bdattoma the project auto selection on the Pipelines page is: https://github.com/opendatahub-io/odh-dashboard/issues/1213

**Comment by kywalker-rh** [comment]
For @jgarciao's first comment I don't follow what UX is needed. If you need help there please elaborate. 

@bdattoma for your question, are you asking to have the row automatically expanded, or something else?

**Comment by kywalker-rh** [comment]
Okay, its starting to make sense. I see the question as, should we create a default name for Runs and Pipelines during creation? I see a couple use-cases where this could be helpful (including if creating either is likely to be automated in the future), so yes, let's do it if we can figure out a reasonable convention.

- For 1: Its not a huge modal, so I don't think its especially terrible to fill out the first (name) field if a user happens to upload a pipeline that includes a name in the yaml before entering a name manually. But if they enter a name first we shouldn't replace it with the name from the yaml.
- For 2: As a default name I think "Run of [pipeline name]" makes sense. The random number suffix feels strange to me, I'd prefer it be some count of the pipeline, or a timestamp rather than random characters.

**Comment by andrewballantyne** [comment]
> * For 2: As a default name I think "Run of [pipeline name]" makes sense. The random number suffix feels strange to me, I'd prefer it be some count of the pipeline, or a timestamp rather than random characters.

A count of *run* -- of Pipeline wouldn't help. But even then, that's weighty... maybe a timestamp -- but are we okay with:

`Run of My Pipeline Name (1685733187121)`

The timestamp is: 'Fri Jun 02 2023 15:13:07 GMT-0400 (Eastern Daylight Time)'

As I type this, it occurs to me we can use the ISO string rather than a ms timestamp -- I bet this is more inline with what you were thinking @kywalker-rh :

`Run of My Pipeline Name (2023-06-02T19:13:07.121Z)`

**Comment by kywalker-rh** [comment]
That's getting long, but it's better than a random number. Looking it up it appears Azure uses the date, and then a number to indicate how many times that pipeline ran that day. So if it was the 4th run of a pipeline today it would automatically be called:

Run of My Pipeline Name 20230603.4

Is that something we can logically do?

**Comment by andrewballantyne** [comment]
Hmmm... there is a concept of filtering we can look into -- it will require us to do a request against the existing runs, but it is possible that will work out... however it will likely delay the create form until we hear back from the server (as it might update mid usage of the form if we do not).

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-18
