### ISSUE TITLE
[Feature Request]: Rename Edit Permission to Contributor

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1335]
### Desired solution

Rename `Edit` to `Contributor` and work with the UX team to get wording of any related text.

We don't want to rework permissions for this use-case, the confusion stems from the name of the role and "edit" in k8s is confusing to the general workings of the UI.

Do more [SelfSubjectAccessReview](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/) checks on the Project list view kebabs... to limit the options they do not have access to.

---

### Feature description

Right now, the `edit` permission used in `Project Sharing` has unwanted effects such as the ones covered in https://github.com/opendatahub-io/odh-dashboard/issues/1320 and https://github.com/opendatahub-io/odh-dashboard/issues/1259.

As discussed [here](https://github.com/opendatahub-io/odh-dashboard/issues/1320#issuecomment-1574417107) we might want to change the role permission to `Contributor` and clearly document what enables.

In early talks, this Contributor role is scoped and can't do the following:

- Delete resources from the dashboard
- Create or edit `Roles` and `RoleBindings`
-  Edit auth tokens in Model Serving

**Comment by andrewballantyne** [comment]
I read the source -- this is a bigger problem than this issue can manage on its own I imagine. We should NOT limit actions that otherwise can be done by K8s... our UI is not the only approach here. We need to disable things with intent when we can't follow through on something, and that should ALWAYS be done by `useCheckAccess` -- I highly discourage any operation done "just because" -- because that WILL fail in time.

**Comment by lucferbux** [comment]
Ok, so what should we do here? Delete this issue and create a tracker for the rework of a new permission? Or should we wait till thursday to see what we decide regarding this matter?

**Comment by bdattoma** [comment]
> We need to disable things with intent when we can't follow through on something, and that should ALWAYS be done by useCheckAccess -- I highly discourage any


@andrewballantyne would this mean that users who cannot Edit/Delete a resource like projects, wouldn't see the options at all? Instead of letting them go through the edit/delete flow and being stopped by the k8s error, like it is today.

**Comment by xianli123** [comment]
Hi @lucferbux @andrewballantyne @bdattoma, did you decide to change the `Edit` to `Contributor`?

**Comment by andrewballantyne** [comment]
> Hi @lucferbux @andrewballantyne @bdattoma, did you decide to change the `Edit` to `Contributor`?

@xianli123 Nope this was decided many many moons ago by UX. Sometime after summit, and sometime before now 🙂 

Do you have a preference beyond this?

---

Some history

- Edit is confusing, edit is k8s technical term -- not really what it grants you
- You can create & delete **most** resources... technically more than just "edit" permissions
- You CANNOT edit the Project
- You have issues creating some resources, like Model Serving's service account / token security stuff -- because it creates a rolebinding, which is only allowed by Admins -- hence why they can only add new people to the project (same resource)

Contributing was decided because that's really what you're doing. You're "contributing" to the project, not really maintaining it / fully managing it. 

Let me know if you want to discuss this further.

**Comment by xianli123** [comment]
@andrewballantyne Thanks, I will research the differences between the edit and contributor in RHODS.

**Comment by kywalker-rh** [comment]
@andrewballantyne @lucferbux Do you need anything from UX to implement this issue? I don't know that there is anything @xianli123 can do here, but maybe you are looking for a content review?

**Comment by xianli123** [comment]
@andrewballantyne @kywalker-rh My bad. I will use the `Contributor` directly.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-582
