### ISSUE TITLE
[Bug]: Pipelines server creation fails on incorrectly formatted s3 endpoint

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you try to create a pipelines server and you configure the aws s3 endpoint to be a url without a scheme, the frontend will throw an error and not create the pipeline server

### Expected Behavior

I expect the s3 endpoint to validate if there is a scheme present as it is required in the pipeline server spec.

i.e.
✅   https://s3.amazonaws.com/
❌   s3.amazonaws.com/

Or at least give a better error message instead of `Cannot read properties of undefined (reading 'replace')`

### Steps To Reproduce

Create a pipeline server with a object storage AWS_S3_ENDPOINT field set to `s3.amazonaws.com/`

### Workaround (if any)

Include a scheme to the url

### What browsers are you seeing the problem on?

Chrome

### Open Data Hub Version

```yml
2.11
```

**Comment by manaswinidas** [comment]
Possible solutions: 
1. Validation warning while entering data in the S3 endpoint field, something like "Please enter a valid URL"(https://www.patternfly.org/v4/components/text-area#validated) or with additional label info(https://www.patternfly.org/v4/components/form/#form-group-with-additional-label-info)
<img width="576" alt="Screenshot 2023-07-04 at 2 41 25 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/f5eaf46b-1c03-4cdf-9283-1ed47654d722">

2. Have a placeholder text with `https://` instead of actual text
3. Append `https://` silently on our side if not present already(without any warning to the user)
4. `https://` or `http://` dropdown beside the URL text box
<img width="237" alt="Screenshot 2023-07-04 at 3 00 40 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/71967067-d53b-4ce2-95a0-b3763622c2bb">

**Comment by andrewballantyne** [comment]
cc @kywalker-rh @yannnz need a UX call here

@guimou @erwangranger would you say `s3.amazonaws.com` is a valid schema? Is it wise to support 

@HumairAK What is expected values of `schema` in the DSPA config?
```
      externalStorage: {
        bucket: string;
        host: string;
        port?: '';
        scheme: string; // <<< we say this is required, because we determine this from the leading characters
        s3CredentialsSecret: {
          accessKey: string;
          secretKey: string;
          secretName: string;
        };
```

**Comment by strangiato** [comment]
+1 to this issue.  Another issue is that once you attempt to create the DS Pipeline and receive the above error message, if you created the connection as part of the pipeline creation, you can't edit the pipeline.  It gives you an error that the connection already exists.  If you switch over to the existing connection, the drop down doesn't include it because the connection didn't exist when the modal was opened.

**Comment by HumairAK** [comment]
>@HumairAK What is expected values of schema in the DSPA config? 

Possible values are `http` and `https`, I have created [a task for dsp team](https://github.com/opendatahub-io/data-science-pipelines-operator/issues/200) to add more meaningful descriptions for the crd fields within the crd spec.

**Comment by andrewballantyne** [comment]
@HumairAK I did mean that -- didn't self check the value I was talking about. Thanks for catching that & the issue you linked to 👍
