### ISSUE TITLE
[Bug]: Custom serving runtimes can have arbitrarily long names

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a custom runtime, users can give it an arbitrarily long display name. This can cause the "serving runtimes" section of the dashboard to break (i.e. buttons get pushed out of reach) if the name is long enough.

We need to address: 

1. Truncate values when there are no spaces in the text

<img width="1523" alt="Screenshot 2023-06-15 at 11 53 37" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/a6e8b7c7-4325-4995-b27d-412e5d8c9338">

### Expected Behavior

Table doesn't expand as large as the name.

Look at using [PF Truncate](https://www.patternfly.org/components/truncate)

### Steps To Reproduce

1. Go to serving runtimes page
2. Create a new serving runtime with a long display name

**Comment by lugi0** [comment]
This issue is still somewhat present in the `Serving runtime` dropdown in the `Add model server` modal.

The text does not wrap (nor is it truncated), and while it does not break the UI it is clear it is extending the name out of bounds of the modal.

I can get the text to wrap by removing the current class from the button element (`pf-c-select__menu-item`) and instead giving it the same class given to the table element in `Serving runtimes` (`pf-u-text-break-word pf-m-width-70`), but it loses the styling of the modal, and using both classes at the same time does not wrap the text, so this might not be a viable solution here.

Attaching a few screenshots for clarity
![3](https://github.com/opendatahub-io/odh-dashboard/assets/82518733/63f6f65a-3b0e-4c95-a185-83210b3f7e5f)
![2](https://github.com/opendatahub-io/odh-dashboard/assets/82518733/c4861c94-3753-4932-b5d4-765fead18ced)
![1](https://github.com/opendatahub-io/odh-dashboard/assets/82518733/2314b9ef-84a4-478c-b439-b2998e5c7cff)

**Comment by lugi0** [comment]
Actually, the UI does break once a model server is deployed using the serving runtime with the long unbreakable word
![image](https://github.com/opendatahub-io/odh-dashboard/assets/82518733/764a0a9c-3f5b-42a3-9641-f508325b875b)

**Comment by andrewballantyne** [comment]
Ah -- we didn't solve it all three spots:

1. [Solved] Settings => Custom Serving Runtimes
2. DS Projects => [project] => Models and model servers section
3. DS Projects => [project] => Create Server => select Runtime dropdown

Seems we need another issue to make sure it's covered in the other two spots. I'll log something in a moment.

**Comment by lucferbux** [comment]
> Ah -- we didn't solve it all three spots:
> 
> 1. [Solved] Settings => Custom Serving Runtimes
> 2. DS Projects => [project] => Models and model servers section
> 3. DS Projects => [project] => Create Server => select Runtime dropdown
> 
> Seems we need another issue to make sure it's covered in the other two spots. I'll log something in a moment.

woopsie, once. i reopened it your message has popped up in the timeline, I'm gonna close it again.
