### ISSUE TITLE
[Feature Request]: Dashboard Service Account should have namespaced admin role

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1465]
### Feature description

We currently have a [namespaced role](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/role.yaml) for the dashboard Service Account in which we add permissions.
We might want to add an [admin role](https://docs.openshift.com/container-platform/4.13/authentication/using-rbac.html#default-roles_using-rbac) to the Service Account in the dashboard namespace.

### Describe alternatives you've considered

We can continue using the current role, but I think we should only control the permission of the Service Account **outside** the dashboard namespace.

**Comment by andrewballantyne** [comment]
A continuation of:

- https://github.com/opendatahub-io/odh-dashboard/issues/1464

**Comment by strangiato** [comment]
The dashboard service account should absolutely not be granted a namespace admin role.  

The operator should be creating a role that grants explicit permissions for only what it needs and nothing more.  This should be following the principle of least privilege.

**Comment by codekow** [comment]
Access to resources should really be defined by the authenticated user and not create a seperate RBAC being managed via the dashboard app.

++ @strangiato Agree with point above

**Comment by andrewballantyne** [comment]
I think this needs further explanation of goals and what we are currently capable of doing. Because the Service Account has a lot of permissions already and we were looking to give it control over the `opendatahub` (or RHODS equiv) namespace to support managing of "product resources".

But given your responses, @strangiato & @codekow, I suspect we need to re-evaluate what permissions it currently has. Because we update `Namespace` resources today.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2959
