### ISSUE TITLE
Disabling a custom Notebook Image from view makes its Workbenches display an Unknown image

### ISSUE THREAD

**Issue by erwangranger** [opendatahub-io/odh-dashboard#1520]
## Status

Might be resolved by:
- https://github.com/opendatahub-io/odh-dashboard/issues/1370

If not, this ticket will need attention.

---

After disabling a custom image, it's still visible in the workbench, but its image is "unknown". 
![image](https://github.com/opendatahub-io/opendatahub-community/assets/32554862/6dc29f8c-370a-43a9-b3e8-6cdb9459d339)

To Reproduce:
1. add a new custom image. Call it "CUSTOM - my image"
2. create a DS project
3. Create a workbench in the project, using that image 
4. Project page displays the right Image name
5. Now, go back to the admin section and disable (not delete) the image
6. Go back to the data science project. (and/or reload the page) 
7. The "notebook Image Column now displays "Unknown". 
8. But you can still start that workbench. 
9. You just cannot create a new workbench with the same Image anymore as it is disabled. 

additional notes:
* re-enabling the image makes its name show up in the project again. 
* fully deleting the image in the admin section for Custom images, also makes the DS project display "unknown", but makes it (expectedly) impossible to spin up the workbench:
 
![image](https://github.com/opendatahub-io/opendatahub-community/assets/32554862/67eb8640-d6a7-4976-8bcf-83b9e858a0dc)

**Comment by DaoDaoNoCode** [comment]
@Gkrumbach07 Can you check if your PR #1872 could also resolve this issue?

**Comment by Gkrumbach07** [comment]
- #1872 
this PR closes #1370 and will preform the following flow:
1. assign a workbench to a custom notebook image
2. disable the image
3. image will no longer be shown as `Unknown`, but as `Image Display Name (deprecated)`
4. editing the workbench requires you to set a new image before submiting
5. re-enabling the image removes the `(deprecated)` text

<img width="923" alt="Screenshot 2023-10-02 at 4 44 08 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/12587674/b0d80056-6bf5-4c52-aed1-aaea04050e63">

@erwangranger does this fix the bug you described?

**Comment by andrewballantyne** [comment]
@kywalker-rh @xianli123 thoughts on the double brackets 🤔

**Comment by erwangranger** [comment]
@Gkrumbach07 , yes, this is definitely better than the existing behavior. 
so, I'm ok with that behavior, as-is, to be the first (and as-soon-as-we-can-have-it) step. 

So, I say, ship it, as-is. 


But if we wanted to then open another quick issue to make this even better, I would say the following should be its description. 

* using "deprecated" is a bit vague, because the image could be either **disabled** by the admin, or wholly **deleted**. So I'd recommend that we display a more meaningful word depending on the situation. 
* A disabled image could be re-enabled easily. 
* A deleted image could be re-created, but not easily.
* While we inform the user of this, we could/should also inform the Admin of the impact of their changes. Sentences like "Disabling an image will mean that new Workbenches will not be able to use it anymore, but existing Workbenches will still be able to use them, although with a `[disabled]` markers added to them". And "Deleting an image will .... etc..." 
* it is understandable that if I change the image of the workbench, I can not pick one that's been disabled. It would be nice however to keep using even a `[disabled]` image if I'm just changing the size of the container. If I'm using a workbench that is usually "small" but on Fridays I need to make it "Large", if someone disables the image, I'm stuck on whatever size was used last. If I need to change the size, I have to "let go" of that image and use something else. And if I do, there is no way to go back to that image without asking the admin to re-enable it. 

If there is time to take some of this into account **without** adding delay to the resolution, great. If not, the rest can wait.

**Comment by Gkrumbach07** [comment]
Maybe not in time for this sprint, because UX will need to go over the proposed changes.

### UX Context
@kywalker-rh, @xianli123, @vconzola  This proposed change is a continuation to https://github.com/opendatahub-io/odh-dashboard/issues/1370 where we added the wording `(deprecated)` to images in the workbench table row if they could not be found (deleted or disabled). This issue is suggesting the following:
- [@kywalker-rh, @xianli123] add `Image Name (disabled)` along with `Image Name (deprecated)` to the workbench table row.
- [@vconzola] adding additional wording to the disable and deleting functions of custom notebooks to inform admins of the impact of their changes (delete or disable)
- [@kywalker-rh, @xianli123] on edit of a workbench using a _disabled_ image, allow the user to make edits without forcing them to select a new image

UX let me know if you have follow up questions

@erwangranger Does this capture what you were hoping to see?

**Comment by erwangranger** [comment]
It does, yes. Thanks.

**Comment by kywalker-rh** [comment]
@Gkrumbach07 and @erwangranger... @xianli123 and @vconzola are out until next week. I would typically defer to them, but in order move this along a bit in the meantime, I agree with the changes for the first and the third bullet. The second one will take some exploration to figure out the best place to surface that text.

I support you moving forward with all the changes except adding the additional wording.

> @kywalker-rh @xianli123 thoughts on the double brackets 🤔

@andrewballantyne It is a little strange, maybe a _- deprecated_ would be more appropriate. I didn't realize we had more brackets in that field.

**Comment by andrewballantyne** [comment]
@Gkrumbach07 give `- deprecated` a shot in your PR... see if that makes things look nicer.

Also I think we can combine these two issues together and merge your PR for both. If we need additional cleanup, we can log those separate. I think this PR context is a lot overlapping with your PR efforts.

**Comment by Gkrumbach07** [comment]
@kywalker-rh why are we trying to work within text by using `- deprecated`. Would using a PF label be best? or will that make the row become to busy?

**Comment by andrewballantyne** [comment]
@Gkrumbach07 mock it up 🙂

**Comment by Gkrumbach07** [comment]
<img width="708" alt="Screenshot 2023-10-04 at 5 49 30 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/12587674/869dee8a-a140-4cb0-9cb3-61e2e104aa16">
<img width="760" alt="Screenshot 2023-10-04 at 5 49 23 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/12587674/b5540c77-3d39-4e95-a09d-d6f6a547d7a3">
<img width="701" alt="Screenshot 2023-10-04 at 5 50 41 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/12587674/d9f2449f-cf7d-43c5-97bb-d018476ca0bd">
<img width="562" alt="Screenshot 2023-10-04 at 5 50 36 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/12587674/f974cc16-23f4-4987-a763-1dcb7d3b03da">

**Comment by erwangranger** [comment]
I like the red icon thing. (is that what PF label is?)

Everything else looks like it could be part of the image name. Which would also be problematic in case  someone actually renames the image with `- deprecated` at the end of the display name.

**Comment by Gkrumbach07** [comment]
@erwangranger Yes this is the [docs](https://www.patternfly.org/components/label) for it. I also made the label `compact` for reference to UX. 

We can also switch up the colors and make deprecated and disabled different colors (grey and red)
<img width="93" alt="Screenshot 2023-10-05 at 8 05 15 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/12587674/20c7280c-6b3a-4e25-b138-6823f6c98503">

**Comment by kywalker-rh** [comment]
Thanks @Gkrumbach07... I really like the label, thank you for proposing it! I want to check on colors, red is definitely very obvious, but that may be good or bad. I'm going to check with the rest of the UX team and respond later today.

**Comment by xianli123** [comment]
Hi @Gkrumbach07 @kywalker-rh @andrewballantyne . I've looked through this issue and all discussions. I prefer labels to double brackets. 

As for the wording, I think "`Disabled`" would be better than "`Deprecated`". The reason is that `Disabled` has an obvious antonym called `Enabled`. Users can easily understand that they or someone else can enable this image again. "`Deprecated`" is more like the result that the user may have violated some rule. Let's wait for others' opinions. 

With regard to the label colors, [PF mentioned that](https://www.patternfly.org/components/label/design-guidelines#color-considerations):
> We recommend you avoid using the red label unless it indicates danger or an error state.

We usually use grey labels in our design to indicate the `Disabled` status. As for the `Deleted` label, we can use the label in orange or red.

In addition, I am not sure if it's possible or necessary to add a popover as shown below to tell users why the image is in that status. (The content of the popover is a rough placeholder.) What do you think?
<img width="647" alt="Screenshot 2023-10-07 at 17 21 17" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/8c551fd7-1085-4b59-97a2-5c4c89e1c0ad">

**Comment by xianli123** [comment]
This is [the design](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=1327%3A9304&type=design&node-id=1452-101032&viewport=444%2C207%2C0.07&t=z3nYvtb1bhDJ8twb-1&scaling=scale-down-width&starting-point-node-id=1452%3A101032&mode=design) based on our discussion in this issue and Slack thread. Please take a look. If there are any suggestions, please leave your comments. 

To summarize the solution:

- Add 2 labels named `Disabled` and `Deleted`. In addition, each label is clickable and can trigger a popover to explain the labels and tell users what they can do. These wordings were reviewed and suggested by @kaedward, our content designer.

- When the notebook image has been deleted and the name is not able to track. It will use the “unknown” in grey color as the name.

**Comment by andrewballantyne** [comment]
Completed by #1872
