### ISSUE TITLE
[Bug]: "We can't find that page" message is display in Dashboard UI once pipeline operator is installed in the background

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

The Data Science Pipelines tab on the Dashboard is intended for showcasing the installed OpenShift Pipeline Operator and utilizing its Pipeline feature. However, if a user proceeds to install the pipeline in the background, the Dashboard page will refresh and display a "We can't find that page" message.

1.

<img width="1836" alt="Screenshot 2023-07-19 at 14 38 51" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/42562189-b083-4818-a07d-31e909de62f8">

2.

<img width="1882" alt="Screenshot 2023-07-19 at 14 38 46" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/192279b0-2cba-4590-bfc6-60eff260cafb">

Although the page design aligns with the approved design, I believe this experience may not be optimal. In my opinion, once the OpenShift Pipeline Operator is installed, it should automatically redirect users to the Pipeline section within the Data Science Pipelines tab, rather than displaying the "We can't find that page" message.

The issue is that when the operator is installed, the user might still be in the ` /dependency-missing/pipelines` routes, so a navigation redirection to the pipelines path is needed

### Expected Behavior

When the operator is installed the dashboard redirects to the pipelines page.

### Steps To Reproduce

1. Uninstall pipelines operator
2. Launch dashboard go to Data Science Pipelines tab
3. Install pipeline operator
4. Keep the Data Science Pipeline open

### Workaround (if any)

Just clicking the sidebar would redirect to the proper page.

**Comment by jbyrne-redhat** [comment]
@lucferbux How does this release notes text sound?

[ODH-DASHBOARD-1547](https://github.com/opendatahub-io/odh-dashboard/issues/1547)
### "We can’t find that page" message displayed in dashboard when pipeline operator installed in background

Previously, when you used the **Data Science Pipelines** page of the dashboard to install the OpenShift Pipelines Operator, when the Operator installation was complete, the page refreshed to show a "We can’t find that page" message. This issue is now resolved. When the Operator installation is complete, the dashboard redirects you to the **Pipelines** page, where you can create a pipeline server.
