### ISSUE TITLE
[Feature Request]: OOTB Model Serving Runtimes need to have visible names/version 

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1577]
### Feature description

Currently, the only thing a customer knows about our serving runtime is that it's called "OpenVino Model Serving Runtime". 

Yes, I could clone it today and call the clone "Erwan's OpenVino Runtime on 2023.06.14". 

But the problem is that over time, we (RHODS) will update the image behind the runtime, and yet the name will remain unchanged. 

So we will end up in a situation where a customer can have 50 distinct Model Servers, created form 12 different versions of the runtime, and not way for them to tell which is which. 

This is a gap. 

We should consider a versioning scheme for the serving runtime, ideally similar to what we do for OOTB notebook images (2023.1, 2023.2, etc..), make that visible to the end-user, and consider the support model thereof. (like adding "deprecated" to the 2023.1 runtime when the 2024.1 runtime is made available.

**Comment by erwangranger** [comment]
Just to add some feedback.

I consider myself pretty knowledgeable on this topic. I was the one who opened the original ticket. And yet ... 

today, I was working with a model server, OVMS, and in Framework drop down, I could only see "Openving_ir" and "onnx". I thought "that's pretty weird, I'm sure I've seen a third choice called 'tensorflow' in the past. Oh well, it must have been a different version of RHODS where I saw that. Good thing I don't need tensorflow". And I moved on. 

Because of what I was doing, I ended up deleting all the models in the project, and the model server. Then I re-created it. And after that, in that newer model server, I suddenly saw all 3 choices again, and then I remembered that the model server I was using up until then had been created many weeks ago. 

All this to say, I said it'd be confusing for people who did not understand the underpinnings, and I think I was right, because it's also confusing for someone who does understand the underpinnings. :-)

**Comment by lucferbux** [comment]
@vconzola Once you are back, this is something worth taking a look, we might wanna work on this asap.
@erwangranger this is part of the roadmap of model serving, we were aiming to have proper versioning for v2 (with version selection and more), but in the meantime we can start creating a workaround here, my thoughts on this would be adding the date of the release or something similar to display so the user is aware of the release version they were using.

What are your thoughts on this?

**Comment by erwangranger** [comment]
Any improvement on this, to make versions more visible, will be a great improvement. Thanks for considering this.

**Comment by lucferbux** [comment]
> Any improvement on this, to make versions more visible, will be a great improvement. Thanks for considering this.

oh thank you to provide helpful feedback, there are a lot of use cases that we didn't considered in dev time, and having someone with customer knowledge to help us out here is amazing!

**Comment by lucferbux** [comment]
Closing this, already tracked in https://issues.redhat.com/browse/RHOAISTRAT-37
