### ISSUE TITLE
[Bug]: Flickering popover and tooltip on open

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/odh-dashboard#1597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2.13.0

### Current Behavior

A popover will snap up to the top right before getting over the element. It only happens on the first instance and then operates cleanly for the rest of the app.

### Expected Behavior

For the snapping behavior to not happen and the modal to open only over the element

### Steps To Reproduce

Open a popover element and see snapping. (see image selector field: "View package information")

### Workaround (if any)

not a breaking change

### What browsers are you seeing the problem on?

Chrome

### Anything else

May need to submit PF issue

**Comment by DaoDaoNoCode** [comment]
After investigation, I found this bug is a PF bug, not related to us. But I am also glad to find that the bug seems to be fixed 2 weeks ago in this [PR](https://github.com/patternfly/patternfly-react/pull/9339). As long as they release and we upgrade to the latest version of PF5, this bug should be fixed automatically.

**Comment by lucferbux** [comment]
@DaoDaoNoCode Ok, so we should take a look and reference this once we update PF!

**Comment by Gkrumbach07** [comment]
fixed in pf5
