### ISSUE TITLE
[Bug]: Leading and trailing spaces are allowed in project, workbench names

### ISSUE THREAD

**Issue by ldimaggi** [opendatahub-io/odh-dashboard#1644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.30

### Current Behavior

In 1.30, the dashboard allows users to create assets (projects, workbenches) with leading and/or trailing spaces in their names. 

### Expected Behavior

Ideally, we would require digits or letters as the first/last characters in an asset name. 

### Steps To Reproduce

1. Create a project or workbench - in the name include leading or trailing spaces

### Workaround (if any)

There doesn't seem to be any functional error - but the spaces could cause problems with searching. 

### What browsers are you seeing the problem on?

Chrome

### Anything else

This bug is related to : https://github.com/opendatahub-io/odh-dashboard/issues/1589

**Comment by lucferbux** [comment]
@ldimaggi we've recently fixed this here https://github.com/opendatahub-io/odh-dashboard/issues/1587 and I think this was targeted for all resources (it was originally raised as a model serving issue). Let me check if it's already fixed in the rest of the resources and in that case we can close this.

**Comment by dpanshug** [comment]
@lucferbux I've checked and it seems like this issue has been resolved. Could you please confirm if we can close this?
