### ISSUE TITLE
[Bug]: Check padding for Projects and Pipelines pages

### ISSUE THREAD

**Issue by manaswinidas** [opendatahub-io/odh-dashboard#1693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2.13.0

### Current Behavior

According to https://github.com/opendatahub-io/odh-dashboard/pull/1634#issuecomment-1671594455 there may be some extra padding in the Projects and Pipelines pages, that we need to check.

### Expected Behavior

Ensure uniform padding on all pages and check whether we need to remove extra spaces between the header and the body(content).

### Steps To Reproduce

1. Go to Global Pipelines page and Projects page and see the padding between the header and the table/content.

**Comment by manaswinidas** [comment]
cc @yannnz @xianli123 @kywalker-rh What is the preferred spacing?

**Comment by xianli123** [comment]
@manaswinidas In the Project page, the space between the header and the table is 16px. I've checked the pipeline's design, the space also is 16px. I propose 16px as the space between the header and table. But wait for @yannnz 's and @kywalker-rh 's thoughts.

**Comment by yannnz** [comment]
vote for 16px  
> @manaswinidas In the Project page, the space between the header and the table is 16px. I've checked the pipeline's design, the space also is 16px. I propose 16px as the space between the header and table. But wait for @yannnz 's and @kywalker-rh 's thoughts.

**Comment by andrewballantyne** [comment]
@yannnz @xianli123 It should be noted this is two sets of 24px. As is by PF PageSection. Are we sure we want to reduce this to 16 from 48 (not sure why they don't support two page sections sharing a single spacing)?

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/31ff76fd-0090-4be4-9fa3-be9f8c61cdf8)

**Comment by xianli123** [comment]
@andrewballantyne In my UI side, I found the bottom padding is 16px. But I am not sure if it follows the original design. I will check it with @kywalker-rh.
<img width="1440" alt="Screenshot 2023-08-28 at 16 10 00" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/9ac3e10f-937a-4b0a-8b88-8ce8d6cab7f6">

**Comment by xianli123** [comment]
@andrewballantyne I will check it with other designers.

**Comment by kywalker-rh** [comment]
@xianli123 is checking with the PF team. I agree with the smaller spacing visually, but don't want to recommend doing something against PF best practices unless we have a good reason.

**Comment by xianli123** [comment]
Hi @andrewballantyne @kywalker-rh I've checked this with the PF4 team and referred to the PF4 guidelines. The space size between the header and the body section is 24px. Here is [the PF4 guideline](https://www.patternfly.org/components/page/design-guidelines#elements). 

In addition, I checked the Openshift UI. The space size between the header and the table is 24px. But we can notice that the table doesn't own top padding as shown in the screenshot below. That makes the header and the table closer to each other. 
<img width="1190" alt="Screenshot 2023-08-31 at 15 52 44" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/74e294d8-218c-4079-9d31-e4258ae51570">

As for RHODS UI, the table has a top padding. That makes the space look larger than the Openshift UI. Can we refer to Openshift's UI to get rid of the top padding of the table? Waiting for others' opinions.
<img width="1440" alt="Screenshot 2023-08-31 at 15 54 38" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/e63162f2-dcfb-42de-9200-12dcb31fea09">

**Comment by christianvogt** [comment]
TBH using OpenShift UI as a comparison isn't ideal because the styling of the app predates many patternfly guidelines. 

I'm with @andrewballantyne in the camp of sticking with PF unless absolutely necessary to break away. One good reason for this is mobile responsive size changes. The PF components are designed in conjunction with one another and therefore have the design guidance built in. For us to start down the path of customizing styles in different ways affects these use cases as well as upgrade paths. eg PF4 => PF5.

Another reason to be strict with PF is consistency with other applications. While we cannot govern what other apps do, adhering to the prescribed layouts of the PF components provides us the best chance of consistency amongst apps.

Here we are using adjacent `PageSection` components which have a prescribed padding on all sides. Removing the top padding is as simple as assigning a PF class. But is removing it absolutely necessary?

I will concede that adjacent `PageSections` with the same background color looks odd with so much padding. I do believe that the intent of the `PageSections` is to produce adjacent sections with different backgrounds in which case the prescribed padding works well (I also very much prefer this look):
![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/f6813870-a43b-4c19-8285-b97109638303)

**Comment by kywalker-rh** [comment]
You are completely right @christianvogt... I checked with the PF team and the entire point of the padding on both sides is for the gray background. I may or may not agree with you about the gray outline :), but I don't want to change the look at the moment, since we are going to be doing a visual design exercise to look at a few pages in the next couple of months and we'll use what comes out of that to adjust visuals as needed.

That said, the PF team gave me this link about removing the padding for pages with 24px x 2: [https://www.patternfly.org/components/page#main-section-padding]. If this doesn't work for us, let's skip it for now, but ideally we can do this easily and end up with 24px spacing instead of 48px, and a bit more space for content on our pages.

**Comment by christianvogt** [comment]
@kywalker-rh The `noPadding` options removes padding from all sides and not just the top. It's simple enough to remove padding from just the top using a custom style or pf utility class (http://v4-archive.patternfly.org/v4/utilities/spacing).

**Comment by kywalker-rh** [comment]
@christianvogt If using the utility class won't make it harder to move to PF v5 in the future let's do it. I just want to be conscious of doing something now that will make the transition more difficult later, so let's only remove the padding if it will be baked into the transition.

**Comment by christianvogt** [comment]
@kywalker-rh afaik these utility classes still exist but with updated names. eg `pf-u-...` => `pf-v5-u...`
I think it's worth putting in a request to PF to own the reduction in padding if `PageSection` components with the same background are rendered adjacent to one and other.

**Comment by kywalker-rh** [comment]
Sounds reasonable to me @christianvogt

**Comment by andrewballantyne** [comment]
@christianvogt have you logged something with PF?

**Comment by christianvogt** [comment]
@andrewballantyne here: https://github.com/patternfly/patternfly-react/issues/9580

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1211
