### ISSUE TITLE
[Feature Request]: Upgrade to Patternfly v5

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1694]
### Status

- #1901 is merged, this is the foundation
- Jupyter Tile has some styling issues
- From memory -- I think the sidebar navigation is also broken (See DS Projects, DS Project Workloads Form, DS Pipelines Create Run for usecases)
- Other areas of the application need to be tested

Work is being conducted on the feature branch `f/pf5-upgrade` -- we will merge this into main when it is sane. Hopefully smaller PRs will be able to be done now to clean up any issues with the UI.

---

### Feature description

Patternfly is now on v5 -- https://www.patternfly.org/

We are still on v4. We should upgrade.

**Comment by andrewballantyne** [comment]
@jenny-s51 Do you know when you'll be able to attempt this upgrade?

**Comment by jenny-s51** [comment]
Hi Andrew, thank you for creating this issue. I started upgrading ODH as soon as PF5 was released, however there were some conflicts due to OpenShift dependencies that are pulled in by ODH. 

As of right now the PF team is working closely with the OpenShift team to help them upgrade their plugins to v5 as soon as possible. Along with ODH, several other products pull in those plugins as dependencies. 

Once OpenShift has upgraded these plugins to v5, it should be smooth sailing for the ODH upgrade and I will plan to continue this effort.

**Comment by lucferbux** [comment]
Ok, I'm gonna link #1597 here cause @DaoDaoNoCode found out that it was addressed in latest PF5 release.

**Comment by andrewballantyne** [comment]
A dependabot PR appears to need Patternfly v5 as well. https://github.com/opendatahub-io/odh-dashboard/pull/1650

**Comment by andrewballantyne** [comment]
FWIW, I asked Jenny to do this. Both because I would like to see this merged and to test her permission powers 🙂

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1786
