### ISSUE TITLE
Review KCS Draft SOPs for RHODS-Dashboard

### ISSUE THREAD

**Issue by maryfrances01** [opendatahub-io/odh-dashboard#1702]
We are in the process of migrating the RHODS Standard Operating Procedures (SOPs) from our internal GitLab repository to the KCS solutions platform. This migration aims to consolidate all SOPs into one accessible location, promoting collaboration across teams including engineering, SRE, and CEE.

This consolidation ensures that anyone working with a customer, and potentially the customers themselves once solutions mature, will have access to this centralized knowledge repository.

As part of this effort, draft KCS SOPs have been created for the existing SOPs. I kindly request the expertise of an engineer to review the draft KCS SOPs and provide feedback on the following two items:

**Accuracy of Commands:** Some SOPs in GitLab lacked precise steps, which have been added to the KCS drafts based on my testing. Please verify the accuracy of commands in the KCS drafts and let me know if any of the steps should be changed/improved.

**Context, Symptoms, and Impact of Alerts Firing:** Provide additional context, symptoms, and impact insights for alerts. If possible, identify dependencies on other components and suggest pre-escalation checks for SRE and CEE teams. Are there any additional checks that SRE or CEE could perform before requesting engineering support, which are not currently outlined in the SOPs?

The KCS drafts for the Dashboard component can be reviewed here:
[7025316](https://access.redhat.com/solutions/7025316)
[7025317](https://access.redhat.com/solutions/7025317)
[7025318](https://access.redhat.com/solutions/7025318)

Feel free to reach out to me with any questions.

**Comment by alexcreasy** [comment]
@andrewballantyne any thoughts on this issue?

**Comment by lucferbux** [comment]
I can help here, I was one of the people who worked defining the previous SOPs, I'll add it to my backlog for this sprint

**Comment by lucferbux** [comment]
I'm gonna add here my comments:

- https://access.redhat.com/solutions/7025316: This is controlling the number of 500 that we get for the `rhods-dashboard` pod, so the first thing to do is check the logs of `rhods-dashboard`, it could be due to isssues in other controllers (such as the one you marked like `odh-notebook-controller` or similar, but we can have different issues (such as login issues we had in the past)
- https://access.redhat.com/solutions/7025317: I don't like the name of this one, in Gitlab the name was misleading, this is `RHODS Dashboard Route Error Burn Rate` and it's checking wether the route is available or not, if not, it could be either the pod is down or even the route hasn't been created
- https://access.redhat.com/solutions/7025318: Is already deprecated, it was checking jupyterhub, which is no longer a component and we don't even have the alert there

This is a first rundown, maybe we need to sync about this, clearly the SOPS were really outdated and with misleading info, if you want more help let me know.

Also @andrewballantyne can you help me out with the `500` errors? I cannot think of which errors can raise 500 right now in the backend.

**Comment by andrewballantyne** [comment]
@lucferbux I responded on slack but failed to bring my answer here -- let me respond here 🙂 

We have been in a lot of back and forth with the SRE team for the RHODS product. We had a lot of "casual" 500 errors when basically our flows hit some issue due to some cause... we may have handled it, logged it, but we didn't really stop 500s from being the response code. This ended up causing a lot of pagers to go off, but in reality it was a no-op problem and fixed itself. We ended up cleaning it up a lot so only noted critical items populated the pager to make the SRE engagement more active when it was needed.

We have not investigated taking critical failures from the UI and pushing it through some mechanism to server-side log it. But we can for sure if there is value. 

Hope that context helps.

**Comment by andrewballantyne** [comment]
@maryfrances01 let us know if you have any questions on the above.

**Comment by lucferbux** [comment]
@maryfrances01 if you want we can have a discussion about this for this sprint.

**Comment by maryfrances01** [comment]
@lucferbux Which would you prefer? Discussing it now or adding any SLIs/SLOs you currently have (along with comments about other SLIs/SLOs needed) and then discussing with a group after others have also commented on the document?

**Comment by lucferbux** [comment]
I'm sorry @maryfrances01 I'm very focused on shipping KServe I didn't check this, yes, you can update the docs with my comments and we can have a follow up conversation to improve them in the future. 
Thanks!

**Comment by lucferbux** [comment]
@maryfrances01 do you think we can close this and add a future issue to expand the docs?

**Comment by maryfrances01** [comment]
@lucferbux Yes, that sounds good.
