### ISSUE TITLE
[Feature Request]: DS Projects details should support K8s `view`

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1706]
### Feature description

We have Admin supported -- Edit mostly supported (I think we have a couple issues still floating about it) but we do not support View at all. Lots of "k8s will tell them no" happening. Including Data Connections are secrets and not available in View.

We should look to support View at some point, but we may need to migrate away from Data Connection Secrets -- if possible.

**Comment by lucferbux** [comment]
This might be a tracker rather than a standalone issue (if it's only the spike to investigate the changes I'm ok with it). But as we've discussed previously, `view` might be a bigger change than expected.

**Comment by alexcreasy** [comment]
@lucferbux @andrewballantyne we've triaged this into ds-projects, not sure if it should be in infra?

**Comment by lucferbux** [comment]
@alexcreasy Yes, this is ds-projects, permissions are self-contained in projects.

**Comment by xianli123** [comment]
Hi @andrewballantyne @alexcreasy @lucferbux I came up with a simple design for the View permission as shown below. What do you think about that?

> <img width="823" alt="Screenshot 2023-10-18 at 17 36 41" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/b9cd505a-a5ce-464e-8bcb-4ae8d4a4100d">

Furthermore, I have been working on the update of the whole permissions UI, because I've seen some drawbacks of the current UI. When I did the new designs, I had some questions about the permissions as listed below.
1.  Can one user have multiple permissions?
2. Can the admin know the members of a Group? 
3. Is it possible to select the existing users? For example, we can provide a list including all available users. At the same time, the admin can also type the user name directly to specify a user.
4. If a user belongs to a group, but the group and the user have different permissions. For example, the group has `Admin` permission and the user has `View` permission. Does the user have both the `Admin` permission and `View` permission?
Please take a look and share your answers. Thanks in advance!

**Comment by andrewballantyne** [comment]
@xianli123 I have replied inline...

> Hi @andrewballantyne @alexcreasy @lucferbux I came up with a simple design for the View permission as shown below. What do you think about that?
> 
> > <img alt="Screenshot 2023-10-18 at 17 36 41" width="823" src="https://github.com/opendatahub-io/odh-dashboard/assets/53931519/b9cd505a-a5ce-464e-8bcb-4ae8d4a4100d">

We should look at probably sorting this from most to least permissions.

Admin => Edit ([renamed to Contributor for our UI](https://github.com/opendatahub-io/odh-dashboard/issues/1335)) => View
(most) => to => (least)

Each is additive in the same vein. View can just see and not modify **most** resources. Edit can modify **most** resources. Admin can do the remaining things Edit could not. 

Note, "modify" in this case means the full rage of CRUD.

If you need to know the difference in what is actually allowed. K8s has decent documentation ([see the table in this section](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles)), if not somewhat technical.

> Furthermore, I have been working on the update of the whole permissions UI, because I've seen some drawbacks that don't fit the new requirements. When I did the new designs, I had some questions about the permissions as listed below.
> 
> 1. Can one user have multiple permissions?

Permissions in K8s is much deeper than this basic overview... but no, they should not have more than one of these.

> 2. Can the admin know the members of a Group?

If they have the power to list groups, they have the power to go to OpenShift Console and see the contents. I know Erwan has spoke of wanting to see the grouped users in the Dashboard UI -- but currently Admins don't really have this power by their role definition. So this has not been a priority (not even sure we have an issue 🤔)

> 3. Is it possible to select the existing users? For example, we can provide a list including all available users. At the same time, the admin can also type the user name directly to specify a user.

Autocomplete of usernames was nixed (by me) during the initial development of the feature. I do not know if we have an easy way to filter on partial name value. K8s doesn't support filtering by partial resource name (User is a resource).

> 4. If a user belongs to a group, but the group and the user have different permissions. For example, the group has `Admin` permission and the user has `View` permission. Does the user have both the `Admin` permission and `View` permission?

Permissions are exclusively additive (once given a permission, you cannot remove it without removing the source). You get the most permissions of all permissions granted to you. So yes, they would be `Admin` foremost because it includes `View` by nature (if it didn't, it would aggregate the two values together).

>    Please take a look and share your answers. Thanks in advance!

**Comment by xianli123** [comment]
@andrewballantyne Thanks for your answer. I will update the order according to `(most) => to => (least)`.

> K8s has decent documentation ([see the table in this section](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles)), if not somewhat technical.

I have read the doc. That's very helpful. Thx!

> they should not have more than one of these.

If so, we should have a mechanism to avoid specifying the existing username with a different permission. Right?

**Comment by andrewballantyne** [comment]
@xianli123 yes, we should definitely unique-ify the values for both user and group.

**Comment by xianli123** [comment]
Ok. I agree. I will do that.

**Comment by xianli123** [comment]
Hi @andrewballantyne I updated the design based on your answers and suggestions that you shared in last Thursday's meeting. Here is [the design link](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=1413%3A96665&type=design&node-id=1823-9721&viewport=235%2C278%2C0.04&t=PnM6yMTiLYuLUaAJ-1&scaling=scale-down-width&mode=design). Please take a look. If there is any questions, please feel free to let me know.

Main updates:
1. Combined the user permissions table and group permissions table.  
2. The view permission is named "Viewer"(noun) instead of "View"(verb), because "Admin" and "Contributor" are nouns. We can keep them consistent.

**Comment by andrewballantyne** [comment]
Sounds good... this functionality will also need to support the special set of rules behind `view`:

* Can't create any resources
* Can't edit any resources
* Doesn't see Data Connections section
* But should be able to use all things -- links to Workbenches, Model Serving routes/tokens for fetching (maybe? @lucferbux I assume the Token is a secret? Is this a problem?)

**Comment by xianli123** [comment]
Hi @kaedward Could you please take a look at [this design](https://www.figma.com/proto/9CkrqD7byqvTBUzRok2ihE/RHODS?page-id=1413%3A96665&type=design&node-id=1823-9721&viewport=235%2C278%2C0.04&t=PnM6yMTiLYuLUaAJ-1&scaling=scale-down-width)? Do you think if the button wording `Assign permission` is accurate? Thanks!

**Comment by shalberd** [comment]
About View not seeing data connections section, due not not being able to list secrets 
"This role does not allow viewing Secrets, since reading the contents of Secrets enables access to ServiceAccount credentials in the namespace, which would allow API access as any ServiceAccount in the namespace (a form of privilege escalation)."

This could also be important to implement with the env variable import into workbenches based on, you got it, secrets.
In terms of listing the dashboard-specific secrets in the namespace, which would be disabled, the dropdown, for View.
I think for View users, the whole Secret section would need to be disabled.

[allow creating workbench env from secrets, issue 1380](https://github.com/opendatahub-io/odh-dashboard/issues/1380#issuecomment-1772760603)

**Comment by kaedward** [comment]
@xianli123 I think "Assign permission" works :-) Was there any pushback on that phrasing?

**Comment by xianli123** [comment]
@kaedward Thanks. Let's go ahead with the "Assign permission".

**Comment by dgutride** [comment]
Move to RFE or get PM weigh in on this.

**Comment by dgutride** [comment]
Migrated to: https://issues.redhat.com/browse/RHOAIENG-2754 - can track this work there.
