### ISSUE TITLE
[Investigation]: Triggered or Scheduled Runs - What is more important?

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1733]
### Feature description

When I've been doing a lot of testing of Pipelines recently, I can confidently say I rarely want to configure, view, or modify a Scheduled run -- and I would imagine most of our users feel the same way. They are not really going to have "live" representations of items.

The Triggered Runs is where all my live data is going to be, I may want to switch between runs to check on results... we currently don't help that use-case, which I believe to be a pretty important use-case of DS Pipelines.

We should either remember the last tab I used -- or (and really) my preference is really to make Triggered the first tab.

cc @yannnz

**Comment by strangiato** [comment]
I was just looking to see if there was an issue related to this before I submitted one myself.

If I am actively working on a pipeline and triggering the pipeline manually, I will most likely want to check the status or results of the pipeline 99% of the time.

If a pipeline is scheduled, I am very unlikely ever to check the status of it unless something has gone wrong.  I may occasionally want to check the run history to see some trends but once gain, most likely because I have noticed something has gone wrong.

There is also probably a larger issue that scheduling a pipeline in general is bad design that should become less necessary as we add more capabilities to DSP.  ML models shouldn't generally be retrained on a set interval "just because".  Instead, ML model retraining should be triggered based on an event such as detection of model drift, updates to data, or updates to code.  Scheduling a training run is really just a way to say "I expect one of these things to happen at a regular interval, so I will just go ahead and plant to retrain."  Since these event based triggers are impossible (or at least require a lot of manual effort to setup) scheduled pipelines an easy solution, but not an ideal one.

**Comment by yannnz** [comment]
@strangiato Thanks for the input!  

For the first case and second case you mentioned, I think the solution is as what @andrewballantyne mentioned above:  remember the last tab the user used. For the first case, if you refresh the page to check the latest runs, it will stay at the Triggered runs tab. For the second case, because as you said, it is unlikely to check the Triggered runs tab, so mostly, it will be Scheduled runs tab unless the user checked the Triggered runs tab. 

For the third use case of adding Event based triggers, I am not sure we support it at the backend nowadays. I will keep this use case in mind when designing the pipeline in the future. I think we will need a separate issue for it if we plan to include it.

**Comment by andrewballantyne** [comment]
Two responses @yannnz 

1. If we "remember" the last choice you made, it will be somewhat odd if you show up a few days later and click on Runs and get the 2nd tab (will the user be puzzled or will they just _remember_?)
    - Side point... per user + browser? per just browser? per single browser session (tab not closed)?
    - Per user has value if the instance is shared / testing multiple users -- not sure how real of a use-case this is
    - Per browser (sorta indefinitely; local storage data) has value, but is awkward as I noted in the no1
    - Per browser session (eg "while I am working on this objective") -- this may not have a lot of value on face value, but see no2
2. Curious why we don't do both of my suggestions -- remember the tab for some time (I recommend browser session) & place the triggered runs tab as the first tab

My two cents of course... we should be able to pivot on this once we get the finer details figured out.

**Comment by strangiato** [comment]
I like the idea of doing both!

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2903
