### ISSUE TITLE
Pipeline Logs Enhancements

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#1746]
Our Pipeline Run log issue https://github.com/opendatahub-io/odh-dashboard/issues/1247 didn't quite deliver our desired UX we wanted. This tracker will serve to track the remaining cleanups of that.

* https://github.com/opendatahub-io/odh-dashboard/issues/1726
* https://github.com/opendatahub-io/odh-dashboard/issues/1734
* https://github.com/opendatahub-io/odh-dashboard/issues/1735
* https://github.com/opendatahub-io/odh-dashboard/issues/1736
* https://github.com/opendatahub-io/odh-dashboard/issues/1737
* https://github.com/opendatahub-io/odh-dashboard/issues/1738
* https://github.com/opendatahub-io/odh-dashboard/issues/1745
* https://github.com/opendatahub-io/odh-dashboard/issues/2226

Additional UX work:
* https://github.com/opendatahub-io/odh-dashboard/issues/1814

Branch:
f/pipelines-enhancement

**Comment by yih-wang** [comment]
Captured the UX improvements mentioned in the incubation review meeting :
- Change the label "Containers" to "Steps"
- Remove the line numbers of the log viewer (because we already have that in the logs) [Done]
- Add error icons to the containers/steps that lead the failure to help users quickly figure out what the error is
- Could add visual hints between tasks and steps to help users understand the relationship between them [Needs further confirmation on the user knowledge of these two concepts]

Potential UX improvements for other features:
- Double-arrows may not accurate to the skipped steps

**Comment by dgutride** [comment]
Replaced by https://issues.redhat.com/browse/RHOAIENG-253

**Comment by dgutride** [comment]
Moving to closed
