### ISSUE TITLE
[BYON] Add support for notebook image inspection or validation when Pipelines are not installed

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#175]
**Is your feature request related to a problem? Please describe.**
The BYON UI should gracefully handle environments where Pipelines are not installed.  

**Possible Solution**
If the cluster does not have Pipelines, the UI should:
- Disable/Hide the 'Status' column since verification can not be performed
--OR--
- Fallback to a k8s native object (Job?) that can perform minimal verification/introspection

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tumido** [comment]
So.. this is not trivial to implement in either case. If pipelines are not available we have a bigger issue - JupyterHub with byon overlay will fail to deploy, since there's no `Pipeline` and `Task` kind on the server. This will cause errors on the operator side.

When it comes to Dashboard (frontend/API), what should be the resulting functionality? Importing things anyway? If so, we need to implement some steps of the import pipeline in the dashboard api backend, like creating imagestreams etc.

Fallback to k8s native object like Job is no use for us, unless we want to have yet another implementation of the tasks of the pipeline and our own task synchronization or what not.

If we've designed BYON with Openshift Pipelines to be our requirement and dependency and accepted that as a design decision, we can't backpaddle from this weeks from release and decide to reimplement it by creating our own workflow controller via Kubernetes Jobs. And I'm not even starting on maintenance of such solution here.

I think we should default to a huge banner on the dashboard BYON page saying: "Install openshift pipelines to enable this functionality", instead of hacking our way around BYON.

**Comment by LaVLaS** [comment]
I don't think there needs to be feature parity between BYON with Pipelines and BYON without pipelines. We will have to support a basic minimal BYON feature set in an environment where Pipelines do not exist.  The strongly recommended path will always be BYON w/ Pipelines but there should be a minimal BYON where the user can use the UI to import an image with minmal validation.

The current feature set for BYON can probably support this minmal workflow but the planned features for the next phases would be restricted to Pipelines only

**Comment by tumido** [comment]
I wonder, doesn't ODH already have a mechanism to add images via a comfigmap or something? Or am I confusing this with something else? If it really does support that, we can leverage it to basically just add entry to that configmap. Or create an imagestream directly.. we would need some further scoping and UI mocks around that, because UI should definitely warn the user before allowing to import images without validation.

**Comment by tumido** [comment]
What about the fallback be:

> Please add following to your KfDef:
> ```
>  - kustomizeConfig:
>       parameters:
>         - name: namespace
>           value: openshift-operators
>       repoRef:
>         name: manifests
>         path: openshift-pipelines/cluster
>     name: openshift-pipelines
> ```

https://github.com/opendatahub-io/odh-manifests/tree/master/openshift-pipelines#openshift-pipelines

**Comment by andrewballantyne** [comment]
This is out of date. We'll add new issues when we sync of the future feature.
