### ISSUE TITLE
[Bug]: JumptToSection scroll in DS Project UI is not working anymore

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/odh-dashboard#1795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.33

### Current Behavior

The navigation menu inside DS Project UI (including also Workbenche Create/Edit page) does not work anymore. It used to work fine in the previous version - regression.

Check the GIF:
![jump](https://github.com/opendatahub-io/odh-dashboard/assets/88311595/397a1fab-514a-460e-8880-d803bb724c8e)

### Expected Behavior

The UI scrolls down to the selected section from the `Jump to section` navigation menu

### Steps To Reproduce

1. create a DS Project
2. click on `Models and model servers section` from the `Jump to section` navigation menu
3. check if the page gets scrolled down to the right section
4. click `Create workbench` button
5. click on `Cluster storage` from the `Jump to section` navigation menu
6. check if the page gets scrolled down to the right section

### Workaround (if any)

None

### Anything else

**This issue is blocking our automated test for the DS Project test suite**

**Comment by lugi0** [comment]
I think this bug is caused by the element `main` with ID `dashboard-page-main`  losing its scrollable property. 
In 1.32 the element was scrollable, but in 1.33 RC1 it's a random `div` nested below it.

`document.getElementById("dashboard-page-main").scrollBy(0,100)` this code used to work, but now it does not anymore. Instead what works is `document.getElementsByClassName("pf-c-drawer__content")[1].scrollBy(0,100)`

**Comment by andrewballantyne** [comment]
Related work: https://github.com/opendatahub-io/odh-dashboard/pull/1571

**Comment by bdattoma** [comment]
@andrewballantyne could we get this fixed for the current release?

**Comment by andrewballantyne** [comment]
Was a hotfix for 1.33 -- officially part of the build for 1.34. Won't make a real difference I imagine, but worth noting why it has both.
