### ISSUE TITLE
[Bug]: Migration not working properly on fresh cluster with GPUs

### ISSUE THREAD

**Issue by FedeAlonso** [opendatahub-io/odh-dashboard#1875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

RHODS 1.33.0

### Current Behavior

Deploying a new cluster with GPUs, the Accelerator dropdown is not shown (neither the old GPU one). 

### Expected Behavior

Accelerator dropdown should be shown so the user can make use of the GPU.

### Steps To Reproduce

From the Dashboard:
1. User creates a new Data Science Project.
2. User navigates to Data Science Projects -> _<created_data_science_project>_ -> Create Workbench
3. The Accelerator dropdown is not shown in the Create Workbench form

### What browsers are you seeing the problem on?

Chrome

### Anything else

The Dashboard Service Account lacks of permissions to create acceleratorprofiles resources, so the migration fails.

**Comment by lucferbux** [comment]
Just to add more context, adding this permission into the `odh-dashboard` role fixed the issue in the cluster we were testing the festure:

```yaml
  - verbs:
      - create
    apiGroups:
      - dashboard.opendatahub.io
    resources:
      - acceleratorprofiles
```

**Comment by lucferbux** [comment]
And the issue that was displaying the pod before applying the fix was this one:

`{"level":50,"time":1695891233347,"pid":17,"hostname":"rhods-dashboard-89dc6b496-2fcwn","msg":"Unable to fully convert GPU to use accelerator profiles. A 403 error occurred when trying to add migrated-gpu accelerator profile: [acceleratorprofiles.dashboard.opendatahub.io](http://acceleratorprofiles.dashboard.opendatahub.io/) is forbidden: User \"system:serviceaccount:redhat-ods-applications:rhods-dashboard\" cannot create resource \"acceleratorprofiles\" in API group \"[dashboard.opendatahub.io](http://dashboard.opendatahub.io/)\" in the namespace \"redhat-ods-applications\""}`

**Comment by Gkrumbach07** [comment]
Just a note so I don't forget, I'm going to also give it list and get permissions because migration will also try to fetch a list of profiles
