### ISSUE TITLE
[Feature Request]: ODH instance validator/fixer 

### ISSUE THREAD

**Issue by krisan** [opendatahub-io/odh-dashboard#1886]
### Feature description

Implement a way (as script or as part of ODH dashboard) to verify if ODH instance is installed and working correctly.

Based on my recent experience with ODH setup - There is a lack of some tools that can verify installation, documentation is also distributed across different repositories. 

Currently, it is difficult to investigate problems, e.g. by monitoring entries in cluster logs. Also, to know that there is a problem - you need to know the entire ODH stack.

My proposed feature is a helper script (or ODH Dashboard reusing the script).
This needs to run as ODH admin (from the dashboard) or as cluster admin (the script).

With this new feature, admins can
- verify that certain ODH features are working/configured correctly (e.g. this will verify that `AcceleratorProfile` for GPU exists and is installed/configured on `opendatahub` namespace)
- This can be used to diagnose all ODH instance components.
- This can be used by developers to regression test and/or detect breaking changes in ODH.
- Each SIG/project can incrementally add other validation features.
- Fix discovered issues 
- Report generated by the tool can be used for bug reporting/support request
- Support versioning (run test against version X of ODH, version Y, etc.)

When script(s) will be implemented first: Dashboard UX can reuse it

When the script will be executed from a local terminal
- admin must be logged in to cluster (`oc login ....`)
- perform diagnosis: `odh-doctor.sh <odh-operator-namespace>`.

### Describe alternatives you've considered

There are no alternatives at the moment.

This feature can be similar to the idea behind `npm doctor`, brew doctor, etc.

**Comment by andrewballantyne** [comment]
We could definitely go with a script to keep status checks available -- but I think it has a lot of value to bring this as a UI too.

I think this would be very cool if we had a page like `Settings => Status` or something that allowed the Admin to invoke a checker that went through the stack and found "known issues" and provided links to docs, a UI page that could be used to fix it, or "quick fix" actions. We could report statuses from k8s resources (maybe even make a CR so component could contribute their desired check path). I think Admins would appreciate this feature.

cc @jwforres @kywalker-rh @jedemo

**Comment by strangiato** [comment]
A lot of this sounds like stuff that should be monitor/reported as status [conditions](https://maelvls.dev/kubernetes-conditions/) by the various operators directly on objects or events associated with objects.

I think that exposing that kind of information is a great idea for the dashboard!  

Reporting these kinds of issues on the DSC object in v2 of the operator was one of the things that I wanted to see improved with the operator redesign.  The operator should be responsible for doing things like checking that tekton is installed when you are deploying DSP and reporting an error when it isn't.  The amq-streams operator (kafka) has also done a great job of utilizing conditions in the past to report depreciated API versions or fields in the past as another example.

Unfortunately there is a pretty large gap in the various operators/controllers for the components in the types of information they report (if they report any at all).  I would love to see a push from all of the component owners own the process of detecting and reporting these types of problems and then the dashboard being able to filter those reported errors up to the users.

**Comment by andrewballantyne** [comment]
Let me cc a couple more people. cc @VaishnaviHire @etirelli 

I'll float this up as a topic to the various meetings too.

**Comment by Gkrumbach07** [comment]
### UX Context
@kywalker-rh ping @andrewballantyne to discuss what this might look like

**Comment by VaishnaviHire** [comment]
Hi All,

Adding here current implementation of operator conditions. However these are not currently reflected in the dashboard. We should be able to extend these to include more information from respective controllers

Operator conditions display if installation is successful for a component. It also displays if a component is in error status .

- Following is status update for every component after installation
![Screenshot 2023-10-02 at 11 00 09 AM](https://github.com/opendatahub-io/odh-dashboard/assets/17230536/ceb4d684-e0c6-4b3f-a110-ea32a2940235)

- Complete set of conditions looks like below
![Screenshot 2023-10-02 at 11 00 44 AM](https://github.com/opendatahub-io/odh-dashboard/assets/17230536/c2b1e4bc-e1ab-498c-afe1-499daa9a7453)

Note above implementation is for v2.x operator. 

From the above conversation, I think we need to update these conditions from simple `Component reconciled successfully` to information returned by individual components.

**Comment by kywalker-rh** [comment]
To add to this, would it also be useful to allow the Admin to turn on or off different features for users? To start this would probably be something as simple as "turn off pipelines functionality on this cluster" but in the future it could be "turn off pipelines for this group of users". This along with the current status and the ability to perform actions to correct any errors sounds like a great idea to me.

**Comment by andrewballantyne** [comment]
> To add to this, would it also be useful to allow the Admin to turn on or off different features for users? To start this would probably be something as simple as "turn off pipelines functionality on this cluster" but in the future it could be "turn off pipelines for this group of users". This along with the current status and the ability to perform actions to correct any errors sounds like a great idea to me.

Yeah, we'll want to expand into this -- only concern with turning features off is what happens to the resources that are in-use... that could be problematic for existing DS Pipeline Server resources, Model Mesh items, etc... so we need to be aware of what "turn something off" really means. But I suspect we could want that functionality. We talked a lot about feature flag power to turn off and on -- those would be far less destructive.

**Comment by strangiato** [comment]
@kywalker-rh These features kind of already exist.

With the v2 operator, the ability to turn off a component is already there.  Just set the component to disabled and the controller for that component gets removed.

With regards to "what does this mean for existing resources"... that follows the standard operator pattern.  You can leave an operand in place when uninstalling a controller and both it and the dependent resources remain in place but unmanaged.  Add the operator back later, and they go back to a managed state.  If you want to clean up those resources, remove the operand instance before uninstalling and the controller will do the cleanup for you.  If you need to clean things up after the operator is uninstalled, then you will need to manually remove the operand and the dependent resources.  CRDs are never removed by an operator uninstall to enable the above workflow and operators must be removed before the CRD can be uninstalled manuall.

Limiting access to specific users for specific features on the k8s side is already there as well with RBAC.  If I didn't want a user to have access to deploy a DSPA, I would likely take the default edit role and create a new custom role with all the same permissions except the ability to create a DSPA.  Then any new user I onboard to the cluster would be assigned that role instead of the default edit role.

I'm not sure if the Dashboard proxies the users access from RBAC today but the openshift console does a great job of handling this where what you see and can do in the console is 100% based on what your RBAC is.  If I don't have permission to view nodes, the nodes section simply doesn't appear in the UI.  The console is simply a reflection of the access a user already has.  It isn't something that needs to be setup or managed outside of RBAC.

ODH could potentially create some new roles that have more limited access to do specific things but that seems like it is opening a can of worms that is ripe to cause issues and confusion when on boarding to the cluster is handled outside of ODH.  The custom roles I describe above usually come with the downside that they require additional maintenance efforts since the custom role is not automatically updated the like default roles on OCP are.  Maybe there is room for a role that has very limited access to only do things like start and stop notebooks and you don't have any other normal permissions to deploy things like models or even create deployments in OCP.  I could see a special role being useful in that case.

Honestly though I'm not sure I could see a use case where this would be commonly used enough that we should put a ton of development time into this.  It can be solved pretty easily in a one off scenario as long as the dashboard respects RBAC.  The use cases I have seen with customer where a custom role is required is 99% of the time driven by weird audit requirements.

> From the above conversation, I think we need to update these conditions from simple Component reconciled successfully to information returned by individual components.

100% agree @VaishnaviHire.  The more intelligent the operator is about the components it is deploying the better.  Any common failures we see when deploying components should report up to the conditions.  I would expect this to grow over time as we learn what kinds of things fail during the deployment of resources.  This also becomes even more important once we start adding more configurable options to the different components in the DSC.

For the individual components we could get the same kind of reporting.  As an example, the DSP operator should be able to do things like report the DSPA can't connect to the S3 instance and report an error condition on the operand or the database PVC is out of space.  Notebook should report when an image can't be pulled is missing a configuration item.

**Comment by andrewballantyne** [comment]
@strangiato FYI, the Dashboard respects RBAC in most of the features; we don't have full UI disabling/hiding checks everywhere, but we have some - ie the infra exists. The exceptions to using the user's K8s RBAC are in the Jupyter Tile & the Admin flows. Everything else _should_ respect and check (to clean up more soon) your state when doing or showing something. If we failed to check on a given item, K8s will stop you if you can't do it as we use the user's token to talk to K8s.

@kywalker-rh there is a lot to unpack from Trevor's & others comments, we should talk more about what our action items can be for this ticket. Carve out a Tracker and see where it sits on our roadmap for both UX and UI efforts.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIRFE-21
