### ISSUE TITLE
[Bug]: Can't create workbench with an empty environment variable

### ISSUE THREAD

**Issue by kaedward** [opendatahub-io/odh-dashboard#1908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

https://console-openshift-console.apps.ui-shared-rhods.dev.datahub.redhat.com/

### Current Behavior

When creating a workbench, if you add an environment variable but don't select an option (leave it empty), you cannot create the workbench but there is no reason given/no red star indicating that it is a required field. 

### Expected Behavior

A warning or red star appears to indicate that the field must be completed or removed before creating a workbench. 

### Steps To Reproduce

1. create a workbench
2. fill out required fields
3. add an environment variable but leave it blank
![Screenshot 2023-10-03 at 3 52 06 PM (1)](https://github.com/opendatahub-io/odh-dashboard/assets/94569315/f8e7c91c-c3fa-4185-9fb9-c0a0d6b611b1)

**Comment by dpanshug** [comment]
## UX Context 

How do we want the forms to work? If you're partially filling up the form value where should this error out? 
cc @xianli123

**Comment by christianvogt** [comment]
Patternfly Form guidelines: https://www.patternfly.org/components/forms/form/design-guidelines#error-validation-on-loss-of-focus
The way I read the Patternfly guidelines suggests that errors appear when leaving / touching fields and when the user submits the form.

As far as this particular issue goes, my suggestion is to simply ignore the unfilled env variable fields since they are not required.

**Comment by xianli123** [comment]
Hi @dpanshug I agree with Chris. We can allow users to save the workbench without variables. Because the **Environment variables** part is not required.

**Comment by adnankhan666** [comment]
https://issues.redhat.com/browse/RHOAIENG-1201
