### ISSUE TITLE
[Story]: Adapt Custom Serving Runtimes to kserve

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#1912]
### Goal

Adapt Custom Serving Runtimes to enable them in different environments

### Dependency issue

No dependencies

### Itemized goals

Logic of the implementation of the annotation: https://github.com/opendatahub-io/odh-dashboard/issues/1940

#### Custom Serving Runtime Table

* Add a column to display the targeted serving platform

#### Custom Serving Runtime Creation

* Add a dropdown to select wether you want Single Model, Multi Modle, or both platforms enabled

### Aspects continued elsewhere

* https://github.com/opendatahub-io/odh-dashboard/issues/1911
* https://github.com/opendatahub-io/odh-dashboard/issues/1940
* https://github.com/opendatahub-io/odh-dashboard/issues/1973

### Mocks

* https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/a/L4ewQGl
* https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/a/71AZ4Yb
* https://www.sketch.com/s/45df001b-2441-4124-a436-5ae1abb409c9/a/27GAdpJ

**Comment by lucferbux** [comment]
The custom logic is not defined yet, it can be an annotation in templates or something similar.

**Comment by lucferbux** [comment]
@andrewballantyne @christianvogt My takeaway with this is just use an annotation for both kserve and modelmesh, if that's ok, we need a follow up with a migration to add that annotation to existing Custom Serving Runtimes

**Comment by andrewballantyne** [comment]
We probably won't have a ton of them to worry about... as I imagine most customers will be picking one or the other... so an annotation is fine. We can pivot later if we find customers use both in high quantities and want to filter at the API level. Make it a JSON array of strings `opendatahub.io/modelServingSupport: "['single', 'multi']"` or something like that. If it is missing the annotation it's for both, otherwise use the value in the array to determine the Runtime use-case.

**Comment by lucferbux** [comment]
Yes that makes total sense

**Comment by lucferbux** [comment]
@DaoDaoNoCode I think you got this clear, but i've updated the description to reflect latest changes and @vconzola 's mocks. Let me know if I've missed something
