### ISSUE TITLE
[Story]: Model global view doesn't hot reload when deleting an inference service

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#2052]
### Goal

Make sure model serving global view reloads the data when an inference service is deleted

### Dependency issue

No dependencies

### Itemized goals

* Make sure model serving global view reloads the data when an inference service is deleted

### Mocks

No mocks

**Comment by christianvogt** [comment]
This happens because the delete API immediately returns as soon as the `deletionTimestamp` is applied to the resource; however the resource may still be fetched. When we perform the refresh, the result may include resources that have started the deletion process and still exist. The deletion process could take some time depending on what is happening with finalizers. 

Here are some options here:
- we can wrap `k8sDeleteResource` to omit resources with a `deletionTimestamp`
- replace our context polling / manual refresh with websockets watch resources
- Handle resources that are in the deletion process with some visual update. Until we have websockets implemented, this state will remain until the next poll interval.
