### ISSUE TITLE
[Bug]: Can't stop Jupyter notebook server as kube:admin

### ISSUE THREAD

**Issue by asharma1304** [opendatahub-io/odh-dashboard#2093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

Downstream version (eg. `RHODS 1.29`)

### Version

1.33

### Current Behavior

Can't stop a deployed Jupyter Notebook server in RHODS when logged in as cluster-admin kube:admin. The notebook controller is accesed from RHODS menu: Applications > Enabled. The command seems to take - there is a pop-up confirming but then nothing happens. When logged in as rhods-admin user, this works. Running OCP version 4.13 with RHODS deployed as an operator. 

### Expected Behavior

Should be able to stop Jupyter notebook server when logged in as kube:admin

### Steps To Reproduce

1. From RHODS dashboard, deploy a Jupyter notebook. 
2. Try to stop the running notebook. 

### Workaround (if any)

Login as rhods-admin and use Stop all Servers from Administration tab  from Applications> Enabled. 

### What browsers are you seeing the problem on?

Chrome

**Comment by manaswinidas** [comment]
cc @andrewballantyne

**Comment by andrewballantyne** [comment]
Thank you for logging the issue. I'm the Dashboard Lead & Architect.

Unfortunately, we don't support kube:admin for a few reasons (you can read those on [this issue here](https://github.com/opendatahub-io/odh-dashboard/issues/2006#issuecomment-1775744411)). If I had to hazard a guess why this happens, it is because kube:admin is not a real user and I believe we have checks in the area to validate the user against the OpenShift Console User resources.

It's unfortunate that it can start by the kube:admin but not stop -- we may investigate why you were able to start in the first place. Since you have a workaround to stop the consumption of the resources. I'm going to go ahead and close this as we have no plans to support kube:admin as it's not a real user account.

If you need to really use kube:admin for testing purposes, I believe the DS Projects' Workbenches work for that user. But I do recommend you no longer use the user in general (see the link above for the reasonings).
