### ISSUE TITLE
[Bug]: Extra spacing in Dropdown toggle text

### ISSUE THREAD

**Issue by dpanshug** [opendatahub-io/odh-dashboard#2127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

main

### Current Behavior

Following the adjustments made in this [PR](https://github.com/opendatahub-io/odh-dashboard/pull/1951) to truncate items within the dropdown, an issue has arisen wherein extra spacing occurs at the beginning of the toggle text.

![Screenshot from 2023-11-11 00-00-10](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/7b3fff4b-2f4b-4196-8fcf-e4bc2603cc03)

### Expected Behavior

Extra spacing should be removed.

### Steps To Reproduce

Open any dropdown and you can see that.

### Anything else

This bug caused by adding Truncate to dropdown items 

https://github.com/dpanshug/odh-dashboard/blob/894d88253fc4b035b7ac4df98524c74fb399f3ff/frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx#L43

**Comment by Gkrumbach07** [comment]
From investigation. this problem is stemming from truncate adding on a min width of `12ch` which for small placeholders like `None` will cause a gap.

Truncate should not have to be used because the dropdown text should truncate by default. The issue is that when this dropdown is in a form, grid is applied which messes with the overflowing

**Comment by Gkrumbach07** [comment]
/assign

Assigning myself becuase this ticket must get in for this sprint
