### ISSUE TITLE
[Tech Debt]: Setup Scripts For Resources

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#2206]
### Type

General Tech Debt (eg. Improve the way something exists today)

### Description

Is there anyway we can get scripts to help with resources we can deploy for standard setup flows -- models, workbenches, data connections, etc...

### Why?

It would be awesome to have a consistent base to work from when you're not really working on those aspects but need them for other uses.

### Anything else?

Will Ansible Playbook be a good solution here?
Kustomize could fill this void (using static values mixed in with variables)

**Comment by lucferbux** [comment]
We can easily deploy several resources with Kustomize and overlays, and it should be fairly straightforward to implement. The real issue is resources that might need sensitive data, for that we can either use a private repo, or some tool like [SOPS](https://github.com/getsops/sops) or [git crypt ](https://github.com/AGWA/git-crypt)

**Comment by dgutride** [comment]
Created Initiative:  https://issues.redhat.com/browse/RHOAIENG-2461
