### ISSUE TITLE
Define the release cadence for dashboard and feature releases

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-dashboard#268]
**Is your feature request related to a problem? Please describe.**
To support regular releases of dashboard and associated features, it would be good to define the release cadence so that developers can ensure that PRs and features are merged intelligently so that each release is feature complete

**Describe the solution you'd like**
A release process that  allows for constant releases that allow for a reproducible deployment at any given release and support the ability for downstream implementations to support cherry-picking commits for hotfixes

**Describe alternatives you've considered**
None at the moment

**Additional context**
N/A

**Comment by andrewballantyne** [comment]
By using milestones and aiming to release (tag) the code on Fridays will allow us to keep a cadence going. If large feature development happens during the week and nothing is ready to be merged into Main by Friday, then we could skip that week's release.

---

## The plan

Release if the following criteria are met (to be refined further).

The ODH Dashboard's `main` branch...

1. has meaningful content merged since last release
2. is in a stable state
3. is requested to be released as a ready-state for downstream / other components


Semver will be used. The code will consider:

* Major versions to be when we have...
    * taken the code in a major architecturally different direction and could have side-effects for features
* Minor versions to be when we have...
    * made a notable existing feature change
    * a new feature being advertised to be turned on
    * a new feature in alpha state (advertise-able but may not be fully feature complete or completely stable)
* Patch versions to be when we have...
    * general bug fixes
    * internal refactors (that do not change the feature set)
    * new features that are not ready to be turned on (*must* be fully behind a feature flag) -- code will still be stable and worked on in feature branches until such time that they are
