### ISSUE TITLE
Improve Jest Setup

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#369]
We have a setup issues for our Jest configuration. Noted on PR #332 [here](https://github.com/opendatahub-io/odh-dashboard/pull/332#discussion_r932112761), we needed to change the way we used lodash.

We should look to make sure Jest is running on the same transform our code runs on so we don't have to adjust our code for testing. 

Links...
https://stackoverflow.com/questions/42260218/jest-setup-syntaxerror-unexpected-token-export
https://how-to.dev/how-to-set-up-jest-for-es-module

**Comment by christianvogt** [comment]
[PR#1536](https://github.com/opendatahub-io/odh-dashboard/pull/1536) made changes to the jest configuration.

While we still use `lodash` and `lodash-es`, when it comes to `lodash-es` we can simply add it to the `transformIgnorePatterns` jest configuration property. This goes for all other 3rd party libraries that end up in the same error. This can be done on a per needs basis. As can be [seen here for the `yaml` library](https://github.com/opendatahub-io/odh-dashboard/blob/93705d6fb44f413c124c42feec5c163fd04d86d2/frontend/jest.config.js#L26).

I don't recall what is the preferred method of using lodash. Whether it's targeted imports or lodash-es etc. That's a whole other issue that requires some investigation with bundle analyzer because PF and other libs use lodash which may import the entirety of lodash anyways.

Closing this issue as the general setup is complete.
