### ISSUE TITLE
[Bug]: Sometimes user gets a 403 Permission Denied after spawning a server

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-dashboard#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that randomly, a user might get the following error message after spawning a server and trying to log in:
![selenium-screenshot-133](https://user-images.githubusercontent.com/82518733/183086455-605609e7-661d-4edd-ab86-25080daf76f2.png)
I am not sure what is causing it, since tests running before and after with the same user ran fine.
I believe the same error can be triggered by deleting the user's cookies while using JL and then trying to log back in again.

### Expected Behavior

User should not see the 403 error, CSRF shouldn't get triggered

**Comment by andrewballantyne** [comment]
This may be difficult to debug, but our redirects should _always_ work -- may take some time to figure out the root cause

**Comment by andrewballantyne** [comment]
I believe this solved by the OAuth changes for DSG. But since I have not seen it, and we have not heard of issues coming out of RHODS tickets. I'm going to assume this is been fixed. We did once have issues with reading pod container statuses, so it may have been related to that effort.

This can be reopened if we run into the issue again.
