### ISSUE TITLE
[KFNBC]: Warn the user when the size option has had issues in the past

### ISSUE THREAD

**Issue by DaoDaoNoCode** [opendatahub-io/odh-dashboard#413]
[ticket reworked from disabling Notebook sizes to informing the user of potential problems]
### Feature description

Based on the discussion in #345, we should also add the ability to detect the viability of the Notebook sizes. We can warn the user when they or other users have had issues spawning a notebook size.

What I think we can do is during the starting of a notebook, look for a given event that indicates issues. After a few moments (TBD of actual time) of this event we can store something into the Dashboard Config(? -- maybe somewhere else is better?) RE: "Size x might have issues"... and then we can present that info to the user.

TBD on UX & Wording. See [Erwan's comment](https://github.com/opendatahub-io/odh-dashboard/issues/413#issuecomment-1217637167) for more context.

**Comment by maroroman** [comment]
@DaoDaoNoCode The old jsp system was imperfect because it could only read the max capacity and max allocatable capacity of a node and not the capacity that was actually available on the cluster. So we can either copy the old implementation and disable notebook sizes only if we know they will not fit on an empty cluster or we can try gathering the information about a node's used capacity from prometheus maybe? cc @samuelvl 

I also think we should add a message explaining that some sizes are unavailable due to size constraints as there was sometimes confusion caused by the sizes disappearing without any notification.

**Comment by samuelvl** [comment]
@maroroman Good idea, we can explore if we get more accurate metrics from Prometheus

**Comment by erwangranger** [comment]
Personally, I think this might be overkill, and also tries to duplicate what is Kubernetes' reason for existing.

In the past, we'd hide the higher sizes only because choosing wrong incurred a 10 minute penalty (timeout). 
With KFNBC ... there should be no penalty. So if after 30 seconds you figure that pod won't ever get running, you can cancel out and choose something smaller. 

Also, looking merely at the nodes and their capacity or utilization is not enough. You'd have to also look at machine pools, to see if potentially, auto-scaling might be able to work. But then you'd have to also look at taints. While all of this is do-able, it is a duplication of the Kubernetes logic of requests, limits, taints, tolerations. 

Finally, you'd also have to account for the cross between GPU and CPU: 
- A "small" notebook with 1 GPU might work
- An XL notebook with 0 GPU might work
- An XL notebook with 1 GPU might fail. (because the GPU nodes are small-ish). 

The hiding behavior has been detrimental in the past. Because of it, I could not:
- Configure machine pools with a minimum number of nodes of zero. 
- Configure Auto-Scaling for GPU nodes. 

IMO, rather than hiding/greying out options, I'd rather we leave the options open and available. At most, I'd add some sort of flag when we figure that the chosen combination might not work. 
A tooltip/label that says "⚠️ this chosen combination is unlikely to result in a running notebook at this time. You can try anyways, but if your notebook does not spawn in a reasonable time, cancel and try again with different parameters".

**Comment by andrewballantyne** [comment]
@kywalker-rh @jedemo -- Thoughts on Erwan's suggestion?

**Comment by kywalker-rh** [comment]
I think @erwangranger's proposal makes sense. My two caveats would be we need the cancel button on the "Starting server" modal, and ideally we also have the event log, so users can determine if there really is a problem. If this proposal is implemented we should run the message by the content design team as well.

**Comment by andrewballantyne** [comment]
I have reworked the ticket to be for what Erwan suggested. Moving away from the very complex "removing/disabling" of items.

This items priority will be based on what Jeff thinks and what our roadmap looks like. This sounds very "extra". More QoL for the user.

**Comment by jedemo** [comment]
I'm ok with relaxing the logic for hiding size & GPU options with some considerations:
1. I still think it makes sense to the GPU drop down if a customer/cluster has not enabled GPUs at all (including auto scaling machine pools). In my opinion, showing the GPU drop down in these cases adds UI clutter and potentially leads to user confusion.
2. I agree with Kyle's comments about the 'cancel' button (which we should already have) and the need for user-friendly error messages in the event log so users can identify issues and change selections in the spawner.

**Comment by andrewballantyne** [comment]
We have had several talks in the past about how to smartly help the user with the deployment. Each time we have tried to get smarter about the GPU stuff, we ended up pushing a fix that blocked another flow. This is not something we are likely to handle in the Dashboard -- we'll rely on K8s events to help the user understand what is and isn't going to work -- no UI smartness to hiding or disabling items is planned.
