### ISSUE TITLE
Address Groups Admin Technical Debt

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#458]
During the final days of development of ODH 2.1 we merged in a not ideal set of code with the intent to come back to update it. There are a few things we can do to improve the maintenance of this code so it fits in with the rest of the codebase, this ticket will layout those issues with some information on why and how. If you wish to talk more @lucferbux I'd be happy to sit down and discuss each in detail.

---

### Avoid PF CSS Overrides

Although we do have a few of these, we should not compound the issue. [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954379290). [Comment ref 2](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954380168).

**Why?** Patternfly has a lot going on, a lot of it internally to make it styled and presentable with a wide variety of support for accessibility. We should not look to get in the way of any contrast styling or impacting spacing that a given style provides. If we give over all component styles to PF, we do not need to concern ourselves with a lot and we benefit a lot.

**How?** Use [PF Layouts](https://www.patternfly.org/v4/layouts/stack) to space things. Use the right [PF Components](https://www.patternfly.org/v4/components/card) to get the desired styles. We should avoid any styles to make something work. If we can't completely avoid it, we must be very sparse with them. Leaning into PF is what it is there for.

---

### Reuse Render Blocks

Don't repeat the same chunks of code, especially large chunks of them. Refactor into their own visual component & provide necessarily non-specific prop names (eg `title`, `description`, etc). [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954379659).

**Why?** During React development, you may run across a grouping of divs/PF components that make up a bigger item. This bigger item doesn't necessarily have to be reused again immediately, but it can help to separate it so the code is easier to rationalize during refactors/bugs. Also if used again immediately, it helps just have less lines of code.

**How?** Take the `FormGroup` into a generic component and pass the necessary props like the `title`, `description` & a state variable for the users that can be passed off to your field. Anything that you don't need to pass in you can just write inline in your component.

---

### Form & Fields

Float state to form when writing new fields. The field is not the source of truth. [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954382917). [Comment ref 2](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954383990). [Comment ref 3](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954385641). [Comment ref 4](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954388371).

**Why?** Fields are probably one of the more complicated items in React to wrap your head around. State should be floated to the parent (or subsequent parents) of all fields. A field only manages its flow and manipulation to generate a render state. "Open state" is something you hold within' a field unless the field explicitly needs to be controlled externally (ie the form has another element that acts upon the open state of a different component).

**How?** Set the props up so the state is not internal. Take a live value, and take an ability to set it. Everything the field does now will be to convert the `value` and call the `setValue`. 

Take the SpawnerPage for example:
```
            <SizeSelectField value={selectedSize} setValue={setSelectedSize} />
            <GPUSelectField value={selectedGpu} setValue={(size) => setSelectedGpu(size)} />
```
Takes a value, sets a value. Also to note `onChange` is a legit name for `setValue` function. It is irrelevant really what the props are called as long as they are generically to the point or context specific.

---

### Minor cleanups:

- Apply to the `GroupSettings` form the `isWidthLimited` property ([docs](https://www.patternfly.org/v4/components/form#form)) -- [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#issuecomment-1227494128)
- Handle optional case behind type of OdhDashboardConfig -- [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954035344)
- Remove eslint-ignore for hook dependencies -- [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954366034)
    - We may want to look at your new hook too, is there more we can do here? It takes A LOT and returns A LOT, maybe needed to be this complex, but we can see about that
- Avoid `try/catch` usage on the frontend, lean into Promises -- [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954385173)
- Files should be named the same as their components -- eg `MenuOptionMultiSelect` is in `MultiSelection.tsx` -- omit `Option` in the name
- What did we do with the `detectUser` call you made? That probably is needed to refresh the user state to see if they did something to their permissions, no? -- [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954373983)
- Avoid constant text -- [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954380770) -- if you think it is needed because of multiple uses, that's likely a call for a component, even an inline one in your component itself
- Convert flatmap -- [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954387161)
- Generic utility for reading your state at empty -- [Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954390341). [Comment ref 2](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954389207).
- `GroupTypes.ts` should be `groupTypes.ts` or `group-types.ts` -- Components are PascalCase, utilities are camelCase or snake-case -- not sure what we do here or if we have a standard... avoid PascalCase for anything that is not directly a component (of the same name)

### Additional items (new ticket(s)?)

- Throwing error if admin is `system:authenticated`; we should look to present this as an issue in the UI -- ([Comment ref](https://github.com/opendatahub-io/odh-dashboard/pull/270#discussion_r954340126))

**Comment by lucferbux** [comment]
- [ ] Avoid PF CSS Overrides -> **No completed**, I've **reduced CSS to the minimum**, but Cards have a different style than the one provided by UX, and is adding more complexity (layout-wise) to the form, and the padding is not formatted.

- [X] Reuse Render Blocks -> Done, now there's a new component based in the Groups form.

- [X] Form & Fields ---> Done, changed the state to be controlled by the parent.

-  [ ] Apply to the `GroupSettings` form the `isWidthLimited` property ([docs](https://www.patternfly.org/v4/components/form#form)) ---> **Not applied**, maybe cause we are using an old version of patternfly, but `maxWidth` is missing from `Form`, and when applying `isWidthLimited` is limited to 500px width.

- [ ] Handle optional case behind type of OdhDashboardConfig --> Done, although I'm not sure if this is the solution you were looking after.

- [X] Remove eslint-ignore for hook dependencies —> Done, changed how to display the error messages

- [ ]  We may want to look at your new hook too, is there more we can do here? It takes A LOT and returns A LOT, maybe needed to be this complex, but we can see about that —> Yes, not done right now, I would love to have a discussion about that, maybe in a different PR.
   
- [X] Avoid `try/catch` usage on the frontend, lean into Promises --> Done

- [X] Files should be named the same as their components -- eg `MenuOptionMultiSelect` is in `MultiSelection.tsx` -- omit `Option` in the name

- [X] What did we do with the `detectUser` call you made? That probably is needed to refresh the user state to see if they did something to their permissions, no? —>  I don’t recall that part, and it’s not present in the code, can’t remember why i added that.

-  [X] Avoid constant text --> Done, you're right, changed

- [X] Convert flatmap --> Done

- [X] Generic utility for reading your state at empty --> Created a constant and a generic function in utils

- [X] `GroupTypes.ts` should be `groupTypes.ts` or `group-types.ts` -- Components are PascalCase, utilities are camelCase or snake-case -- not sure what we do here or if we have a standard... avoid PascalCase for anything that is not directly a component (of the same name)

- [ ]  Throwing error if admin is `system:authenticated`; we should look to present this as an issue in the UI --> I would further discuss this one, cause right now if it’s added by force, the system will clean up the group since it doesn’t exist.
