### ISSUE TITLE
[Bug]: Routes can be more secure

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our backend is currently run by the service account (on cluster -- in dev it's your user). This grants unneeded access to the user. If the user requests resources that are not theirs, the service account still fetches them.

### Expected Behavior

What we need to do is limit the effort behind requesting resources that are not yours. It won't be perfect, DSG will help us constrain things better to a namespace.

### Steps To Reproduce

Make a direct URL request to get a resource you don't own (as the logged in user) -- ie: https://$DASHBOARD_URL/api/configmaps/kube-system/bootstrap

### Workaround (if any)

None -- the service account makes the actual request so there is no limitation of Roles to prevent this.

### Open Data Hub Version

```yml
2.0 (RHODS 1.15+)
```

**Comment by lucferbux** [comment]
I'm just gonna leave here the testing to ensure this bug is closed:

# Testing

## Overview

* You cannot access if not logged in in openshift

## Tested images

* Main image: quay.io/lferrnan/odh-dashboard-test:v21
* Bugfix image: quay.io/lferrnan/odh-dashboard-test:add-route-security

## Namespaces

* Dashboard: opendatahub
* Notebook: odh-notebook
* Outside: openshift-operators


## Deploying a notebook

**Main branch**

✅ You can deploy it

**Bugfix branch**

✅ You can deploy it

## Accessing a configmap outside the dashboard namespace

```bash
❯ oc get configmap kube-root-ca.crt  -n openshift-operators
NAME                    DATA   AGE
kube-root-ca.crt   1      17d
```

https://odh-dashboard-opendatahub.apps.lferrnan-odh.dev.datahub.redhat.com/api/configmaps/openshift-operators/kube-root-ca.crt  

**Main branch**

🐞 You can access 

**Bugfix branch**

✅ **You can’t access** —> `{"statusCode":403,"error":"Forbidden","message":"Cannot request a resource outside of the notebook namespace"}`



## Accessing a configmap inside the dashboard namespace

```bash
❯ oc get configmap notebook-controller-config -n opendatahub
NAME                                      DATA   AGE
notebook-controller-config   3      17d
```

https://odh-dashboard-opendatahub.apps.lferrnan-odh.dev.datahub.redhat.com/api/configmaps/opendatahub/notebook-controller-config 

**Main branch**

✅ You can access

**Bugfix branch**

✅ You can access


## Accessing a configmap inside the notebook namespace

```bash
❯ oc get configmap jupyterhub-singleuser-profile-lferrnan-envs -n odh-notebook
NAME                                          DATA   AGE
jupyterhub-singleuser-profile-lferrnan-envs   0      2m39s
```

https://odh-dashboard-opendatahub.apps.lferrnan-odh.dev.datahub.redhat.com/api/configmaps/odh-notebook/jupyterhub-singleuser-profile-lferrnan-envs 

**Main branch**

✅ You can access

**Bugfix branch**

✅ You can access

## Accessing a secret outside the dashboard namespace

```bash
❯ oc get secret deployer-dockercfg-v8kxj  -n openshift-operators
NAME                       TYPE                      DATA   AGE
deployer-dockercfg-v8kxj   kubernetes.io/dockercfg   1      17d
```

https://odh-dashboard-opendatahub.apps.lferrnan-odh.dev.datahub.redhat.com/api/secrets/openshift-operators/deployer-dockercfg-v8kxj 

**Main branch**

🐞 You can access 

**Bugfix branch**

✅ **You can’t access** —> `{"statusCode":403,"error":"Forbidden","message":"Cannot request a resource outside of the notebook namespace"}`


## Accessing a secret inside the dashboard namespace

```
❯ oc get secret odh-dashboard-token-6v42t -n opendatahub
NAME                        TYPE                                  DATA   AGE
odh-dashboard-token-6v42t   kubernetes.io/service-account-token   4      16d
```

https://odh-dashboard-opendatahub.apps.lferrnan-odh.dev.datahub.redhat.com/api/secrets/opendatahub/odh-dashboard-token-6v42t 

**Main branch**

✅ You can access

**Bugfix branch**

✅ You can access

## Accessing a secret inside the notebook namespace

```
❯ oc get secret jupyter-nb-lferrnan-tls  -n odh-notebook
NAME                      TYPE                DATA   AGE
jupyter-nb-lferrnan-tls   kubernetes.io/tls   2      9m39s
```

https://odh-dashboard-opendatahub.apps.lferrnan-odh.dev.datahub.redhat.com/api/secrets/odh-notebook/jupyter-nb-lferrnan-tls 

**Main branch**

✅ You can access

**Bugfix branch**

✅ You can access
