### ISSUE TITLE
[Bug]: Configmap feature flag is overriden by the dashboard

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to disable one application in the `odh-enabled--applications-config`, it will be overridedn if the kfdef of that application exists. This is due to this logic: https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/resourceUtils.ts#L274

Right here it will check if the **application's kfdef** exists, and if so, just enable it and update the configmap, so If you had that application disabled it will revert back to enable.

### Expected Behavior

When you change a value in the configmap, the state of the application chagens and it reflects the status that you've selected.

### Steps To Reproduce

1. Open `odh-enabled--applications-config`.
2. Change `jupyter` to `false` (or straight up delete the configmap).
3. Reload the dashboard and wait for the watcher to be triggered it again (around 2 mins).
4. The value in the configmap will be reverted to `true`.

**Comment by DaoDaoNoCode** [comment]
I have some questions about the opinion here. The file `odh-enabled--applications-config` is used to record whether an application is available or not and show the enabled or disabled status on `Enabled` page, it's not designed to be manually changed. It's always checked by odh-dashboard backend and updated by the logic. So this is the expected behavior. When the application has kfdef and the kfdef exists, the application should be REALLY enabled. So this is the right behavior to overwrite the  `odh-enabled--applications-config` to set it to true, and this configmap should never be manually changed, it's just a flag set by the dashboard via some logic.
cc @andrewballantyne @maroroman @dlabaj

**Comment by dlabaj** [comment]
This config map is used show what is on the enabled page.  I don't understand why we would prevent this from being updated manually.  Once you enable an app it never can unenabled.  I understand we don't do that through the UI yet, but I think it's a valuable feature to have.  @DaoDaoNoCode Is there a reason why we wouldn't want to allow someone to not remove an app from the enable page.

**Comment by dlabaj** [comment]
I do think that we should use features.json to disable an app all together since it will remove documenation, and quick starts where this won't.

**Comment by lucferbux** [comment]
Closing this as an outcome of the discussion we had earlier.

**Comment by lucferbux** [comment]
Closing this as an outcome of the discussion we had earlier.
