### ISSUE TITLE
[Feature Request]: Add admin activity logging

### ISSUE THREAD

**Issue by maroroman** [opendatahub-io/odh-dashboard#717]
### Feature description

For security purposes, admin activity tracking should be implemented in any affected areas of the dashboard.

**Comment by andrewballantyne** [comment]
This issue has implications to the way our infrastructure works. We'll need to investigate this with the architects and see what we can make happen to get us where we need to be. 

We have very limited logging today, both in the client and backend so we'll need to think on how we can approach to giving a better stage.

Initial thoughts I have are:
- Client should not be trusted for high-tier tracking, telemetry probably should be okay to track user activity around the client
- Backend does everything to add, remove, update or otherwise touch the resources in k8s
    - All calls could be logged? And whom made them (OAuth token -- username)
    - Does k8s help us out here? In the end all changes are k8s driven, we don't have our own storage (ignoring the weirdness of the serviceaccount doing everything for the Juypter tile)
    - Pass-through API is very simple, it could log the user as it passes through our backend -- we already do some of that logging for development (info logs), we could increase that effort for production (different log level or alternative log-like storage)

**Comment by andrewballantyne** [comment]
Bumped this to Blocker as we need it for RHODS 1.21 (as it stands today). This will need to be delivered by the end of next week

cc @jkoehler-redhat

**Comment by andrewballantyne** [comment]
Can't get it into next release -- functionality issues with the PR. Will try for the following release.

**Comment by andrewballantyne** [comment]
If Landon can manage it -- https://github.com/opendatahub-io/odh-dashboard/pull/914 should merge before release tomorrow. So I added this ticket back to the milestone.
