### ISSUE TITLE
[Model Serving]: Improve NumberInput validation logic 

### ISSUE THREAD

**Issue by lucferbux** [opendatahub-io/odh-dashboard#818]
### Feature description

Right now, we have a plain `onChange` logic in the `NumberInput` component for the `ServingRuntime` modal. You can enter 0 values even though the minimum value is `1`. We get an error when entering a 0 in the input field, but so far this could be handled better.

### Describe alternatives you've considered

Adding more logic to the `onChange` function rather than relying in the `validated` prop.

**Comment by vconzola** [comment]
@lucferbux I assume you're already setting the min Prop to 1 for the component to prevent users from using the button to decrement to 0? Looking at the component it appears this should also prevent the user form typing in a 0 - it should automatically set the value to 1 . At least that's what happens when you try to type in a value larger than the upper threshold in this example: https://www.patternfly.org/v4/components/number-input#with-unit-and-thresholds.

**Comment by andrewballantyne** [comment]
Whomever picks this up, let me know if you have any questions on the React flow.

**Comment by lucferbux** [comment]
Noted, got a PR for this right now
