### ISSUE TITLE
[Feature Request]: Improve Notebook Logout Experience

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/odh-dashboard#892]
### Feature description

When logging out of the Jupyter Notebook it redirects to our Dashboard -- which uses a `window.location` redirect to the OAuth container for that Notebook -- which then redirects back to us at a more specific location (either the control panel for the jupyter tile or the project the notebook belongs to).

What we should do is look to see if we can make a direct get call or something using `fetch` or `axios` or something -- when we get a response, we can react-router redirect and keep the flow a lot cleaner.

It's a messy back and forth right now.

### Describe alternatives you've considered

Possible we spawn a new tab to do this? Not sure this is any more ideal -- and browsers could probably mute this action so we might be out of luck if the primary goal fails.

**Comment by DaoDaoNoCode** [comment]
Test results with the changes in #1792 

Data science project:
No change. When the logout button is hit, it will go to `${dashboard_origin}/notebook/${project_name}/${notebook_name}/logout` page, where we create a redirect component to help replace the URL with the Jupyter Notebook URL and add `/oauth/sign_out` to **really** sign out the oauth proxy. After the sign out, it will then check the annotation `notebooks.opendatahub.io/oauth-logout-url`, which will finally redirect the user back to the project details page and add a logout param to help show the notification to indicate successful logout.

Jupyter tile:
Similar to above, first navigate to `${dashboard_origin}/notebook/${dashboard_namespace}/${notebook_name}/logout` page, then fetch the route there and add `/oauth/sign_out` to the URL to sign out. After that, it checks the annotation too, and navigates back to the notebook controller page. The only difference here is the Jupyter tile notebook doesn't add a search param later, so it will not even show a notification for the successful logout.

So the issue is still there and we may need to figure out a way to better handle it.

**Comment by harshad16** [comment]
On Notebook-controller end, we are also trying to find a solution on our end for this.
Issue: https://github.com/opendatahub-io/kubeflow/issues/157

**Comment by andrewballantyne** [comment]
Similar but not the same issue @harshad16 -- that, however, has been discussed before so I'm glad you have something logged 🎉 

This is about when our Dashboard hard refreshes/redirects after being sent back from JupyterLab -- this should be entirely a flow on our side as I understand the issue.

**Comment by harshad16** [comment]
Thank you for clarifying the difference, if we find some insights
will share them with you.

**Comment by dgutride** [comment]
Migrated to:  https://issues.redhat.com/browse/RHOAIENG-2744
